# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c6f21ffbed586c0afdecbd6504431c1b5b75d60e18f7a21e135291ac3a00b53fb1645bbc02534a15911dcbe0f2ca22231987b3bbc0c0010ffb53d4d4c64546

test:
  secret_key_base: 020e6efc50fc85e32f8bb6643fa128731c94c795c66df7333ac20faf4eddea82f1bec2a5d90f1be5e655608f86867256949755c6155f3b5e548840543331f1d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
